#############################################################################
# Makefile for building: IMTool
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu Jul 28 03:34:03 2016
# Project:  IMTool.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile IMTool.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread -lprotobuf 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		imclient.cpp \
		imdatapack.cpp \
		GateServiceMsg.pb.cc moc_mainwindow.cpp \
		moc_imclient.cpp
OBJECTS       = main.o \
		mainwindow.o \
		imclient.o \
		imdatapack.o \
		GateServiceMsg.pb.o \
		moc_mainwindow.o \
		moc_imclient.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		IMTool.pro
QMAKE_TARGET  = IMTool
DESTDIR       = 
TARGET        = IMTool

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IMTool.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile IMTool.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile IMTool.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/IMTool1.0.0 || $(MKDIR) .tmp/IMTool1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/IMTool1.0.0/ && $(COPY_FILE) --parents mainwindow.h imclient.h imtool.h imdatapack.h GateServiceMsg.pb.h .tmp/IMTool1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp imclient.cpp imdatapack.cpp GateServiceMsg.pb.cc .tmp/IMTool1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/IMTool1.0.0/ && (cd `dirname .tmp/IMTool1.0.0` && $(TAR) IMTool1.0.0.tar IMTool1.0.0 && $(COMPRESS) IMTool1.0.0.tar) && $(MOVE) `dirname .tmp/IMTool1.0.0`/IMTool1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/IMTool1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_imclient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_imclient.cpp
moc_mainwindow.cpp: imclient.h \
		imtool.h \
		ui_mainwindow.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_imclient.cpp: imtool.h \
		ui_mainwindow.h \
		imclient.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) imclient.h -o moc_imclient.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		imclient.h \
		imtool.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		imclient.h \
		imtool.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

imclient.o: imclient.cpp imclient.h \
		imtool.h \
		ui_mainwindow.h \
		imdatapack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imclient.o imclient.cpp

imdatapack.o: imdatapack.cpp imdatapack.h \
		imtool.h \
		ui_mainwindow.h \
		GateServiceMsg.pb.h \
		google/protobuf/stubs/common.h \
		google/protobuf/generated_message_util.h \
		google/protobuf/message.h \
		google/protobuf/message_lite.h \
		google/protobuf/descriptor.h \
		google/protobuf/repeated_field.h \
		google/protobuf/stubs/type_traits.h \
		google/protobuf/stubs/template_util.h \
		google/protobuf/extension_set.h \
		google/protobuf/unknown_field_set.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imdatapack.o imdatapack.cpp

GateServiceMsg.pb.o: GateServiceMsg.pb.cc GateServiceMsg.pb.h \
		google/protobuf/stubs/common.h \
		google/protobuf/generated_message_util.h \
		google/protobuf/message.h \
		google/protobuf/message_lite.h \
		google/protobuf/descriptor.h \
		google/protobuf/repeated_field.h \
		google/protobuf/stubs/type_traits.h \
		google/protobuf/stubs/template_util.h \
		google/protobuf/extension_set.h \
		google/protobuf/unknown_field_set.h \
		google/protobuf/stubs/once.h \
		google/protobuf/stubs/atomicops.h \
		google/protobuf/stubs/platform_macros.h \
		google/protobuf/stubs/atomicops_internals_x86_msvc.h \
		google/protobuf/stubs/atomicops_internals_macosx.h \
		google/protobuf/stubs/atomicops_internals_x86_gcc.h \
		google/protobuf/stubs/atomicops_internals_arm_gcc.h \
		google/protobuf/stubs/atomicops_internals_arm_qnx.h \
		google/protobuf/stubs/atomicops_internals_mips_gcc.h \
		google/protobuf/stubs/atomicops_internals_pnacl.h \
		google/protobuf/stubs/atomicops_internals_atomicword_compat.h \
		google/protobuf/io/coded_stream.h \
		google/protobuf/wire_format_lite_inl.h \
		google/protobuf/wire_format_lite.h \
		google/protobuf/generated_message_reflection.h \
		google/protobuf/generated_enum_reflection.h \
		google/protobuf/reflection_ops.h \
		google/protobuf/wire_format.h \
		google/protobuf/descriptor.pb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GateServiceMsg.pb.o GateServiceMsg.pb.cc

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_imclient.o: moc_imclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imclient.o moc_imclient.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

